module:
  imports:
    - path: github.com/FortAwesome/Font-Awesome
      mounts:
        - source: svgs
          target: assets/svgs/fontawesome
    - path: github.com/twbs/icons
      mounts:
        - source: icons
          target: assets/svgs/bootstrap
